// NSE 500 (Nifty 500) constituents. Yahoo Finance symbols use the `.NS` suffix.
// This list is representative and may need periodic refresh as the index reconstitutes.
export interface NseStock {
  symbol: string; // Yahoo symbol e.g. RELIANCE.NS
  name: string;
}

export const NSE_500: NseStock[] = [
  { symbol: "RELIANCE.NS", name: "Reliance Industries" },
  { symbol: "TCS.NS", name: "Tata Consultancy Services" },
  { symbol: "HDFCBANK.NS", name: "HDFC Bank" },
  { symbol: "BHARTIARTL.NS", name: "Bharti Airtel" },
  { symbol: "ICICIBANK.NS", name: "ICICI Bank" },
  { symbol: "INFY.NS", name: "Infosys" },
  { symbol: "SBIN.NS", name: "State Bank of India" },
  { symbol: "LICI.NS", name: "Life Insurance Corporation of India" },
  { symbol: "HINDUNILVR.NS", name: "Hindustan Unilever" },
  { symbol: "ITC.NS", name: "ITC" },
  { symbol: "LT.NS", name: "Larsen & Toubro" },
  { symbol: "HCLTECH.NS", name: "HCL Technologies" },
  { symbol: "BAJFINANCE.NS", name: "Bajaj Finance" },
  { symbol: "SUNPHARMA.NS", name: "Sun Pharmaceutical" },
  { symbol: "MARUTI.NS", name: "Maruti Suzuki" },
  { symbol: "KOTAKBANK.NS", name: "Kotak Mahindra Bank" },
  { symbol: "M&M.NS", name: "Mahindra & Mahindra" },
  { symbol: "AXISBANK.NS", name: "Axis Bank" },
  { symbol: "NTPC.NS", name: "NTPC" },
  { symbol: "ULTRACEMCO.NS", name: "UltraTech Cement" },
  { symbol: "ONGC.NS", name: "Oil & Natural Gas Corporation" },
  { symbol: "TITAN.NS", name: "Titan Company" },
  { symbol: "ADANIENT.NS", name: "Adani Enterprises" },
  { symbol: "ADANIPORTS.NS", name: "Adani Ports & SEZ" },
  { symbol: "POWERGRID.NS", name: "Power Grid Corporation" },
  { symbol: "WIPRO.NS", name: "Wipro" },
  { symbol: "JSWSTEEL.NS", name: "JSW Steel" },
  { symbol: "BAJAJFINSV.NS", name: "Bajaj Finserv" },
  { symbol: "COALINDIA.NS", name: "Coal India" },
  { symbol: "ASIANPAINT.NS", name: "Asian Paints" },
  { symbol: "NESTLEIND.NS", name: "Nestle India" },
  { symbol: "TATAMOTORS.NS", name: "Tata Motors" },
  { symbol: "BEL.NS", name: "Bharat Electronics" },
  { symbol: "TATASTEEL.NS", name: "Tata Steel" },
  { symbol: "TRENT.NS", name: "Trent" },
  { symbol: "HINDALCO.NS", name: "Hindalco Industries" },
  { symbol: "GRASIM.NS", name: "Grasim Industries" },
  { symbol: "HAL.NS", name: "Hindustan Aeronautics" },
  { symbol: "JIOFIN.NS", name: "Jio Financial Services" },
  { symbol: "DRREDDY.NS", name: "Dr. Reddy's Laboratories" },
  { symbol: "SBILIFE.NS", name: "SBI Life Insurance" },
  { symbol: "EICHERMOT.NS", name: "Eicher Motors" },
  { symbol: "BAJAJ-AUTO.NS", name: "Bajaj Auto" },
  { symbol: "INDUSINDBK.NS", name: "IndusInd Bank" },
  { symbol: "TECHM.NS", name: "Tech Mahindra" },
  { symbol: "HDFCLIFE.NS", name: "HDFC Life Insurance" },
  { symbol: "CIPLA.NS", name: "Cipla" },
  { symbol: "DMART.NS", name: "Avenue Supermarts" },
  { symbol: "VEDL.NS", name: "Vedanta" },
  { symbol: "PIDILITIND.NS", name: "Pidilite Industries" },
  { symbol: "DIVISLAB.NS", name: "Divi's Laboratories" },
  { symbol: "BPCL.NS", name: "Bharat Petroleum" },
  { symbol: "TATACONSUM.NS", name: "Tata Consumer Products" },
  { symbol: "GODREJCP.NS", name: "Godrej Consumer Products" },
  { symbol: "BRITANNIA.NS", name: "Britannia Industries" },
  { symbol: "APOLLOHOSP.NS", name: "Apollo Hospitals" },
  { symbol: "HYUNDAI.NS", name: "Hyundai Motor India" },
  { symbol: "SHREECEM.NS", name: "Shree Cement" },
  { symbol: "AMBUJACEM.NS", name: "Ambuja Cements" },
  { symbol: "DLF.NS", name: "DLF" },
  { symbol: "TVSMOTOR.NS", name: "TVS Motor Company" },
  { symbol: "ZOMATO.NS", name: "Eternal (Zomato)" },
  { symbol: "PNB.NS", name: "Punjab National Bank" },
  { symbol: "BANKBARODA.NS", name: "Bank of Baroda" },
  { symbol: "IOC.NS", name: "Indian Oil Corporation" },
  { symbol: "GAIL.NS", name: "GAIL India" },
  { symbol: "ADANIGREEN.NS", name: "Adani Green Energy" },
  { symbol: "ADANIPOWER.NS", name: "Adani Power" },
  { symbol: "SIEMENS.NS", name: "Siemens" },
  { symbol: "ABB.NS", name: "ABB India" },
  { symbol: "HAVELLS.NS", name: "Havells India" },
  { symbol: "ICICIPRULI.NS", name: "ICICI Prudential Life" },
  { symbol: "ICICIGI.NS", name: "ICICI Lombard General Insurance" },
  { symbol: "CHOLAFIN.NS", name: "Cholamandalam Investment" },
  { symbol: "INDIGO.NS", name: "InterGlobe Aviation" },
  { symbol: "NAUKRI.NS", name: "Info Edge India" },
  { symbol: "PFC.NS", name: "Power Finance Corporation" },
  { symbol: "RECLTD.NS", name: "REC" },
  { symbol: "IRFC.NS", name: "Indian Railway Finance" },
  { symbol: "LODHA.NS", name: "Macrotech Developers" },
  { symbol: "BOSCHLTD.NS", name: "Bosch" },
  { symbol: "TORNTPHARM.NS", name: "Torrent Pharmaceuticals" },
  { symbol: "TORNTPOWER.NS", name: "Torrent Power" },
  { symbol: "CGPOWER.NS", name: "CG Power & Industrial Solutions" },
  { symbol: "ZYDUSLIFE.NS", name: "Zydus Lifesciences" },
  { symbol: "LUPIN.NS", name: "Lupin" },
  { symbol: "MOTHERSON.NS", name: "Samvardhana Motherson" },
  { symbol: "INDHOTEL.NS", name: "Indian Hotels" },
  { symbol: "PIIND.NS", name: "PI Industries" },
  { symbol: "MARICO.NS", name: "Marico" },
  { symbol: "COLPAL.NS", name: "Colgate Palmolive India" },
  { symbol: "DABUR.NS", name: "Dabur India" },
  { symbol: "BERGEPAINT.NS", name: "Berger Paints India" },
  { symbol: "MUTHOOTFIN.NS", name: "Muthoot Finance" },
  { symbol: "BAJAJHLDNG.NS", name: "Bajaj Holdings" },
  { symbol: "SHRIRAMFIN.NS", name: "Shriram Finance" },
  { symbol: "SBICARD.NS", name: "SBI Cards & Payment Services" },
  { symbol: "HDFCAMC.NS", name: "HDFC AMC" },
  { symbol: "IDBI.NS", name: "IDBI Bank" },
  { symbol: "IDFCFIRSTB.NS", name: "IDFC First Bank" },
  { symbol: "FEDERALBNK.NS", name: "Federal Bank" },
  { symbol: "CANBK.NS", name: "Canara Bank" },
  { symbol: "UNIONBANK.NS", name: "Union Bank of India" },
  { symbol: "INDIANB.NS", name: "Indian Bank" },
  { symbol: "AUBANK.NS", name: "AU Small Finance Bank" },
  { symbol: "BANDHANBNK.NS", name: "Bandhan Bank" },
  { symbol: "RBLBANK.NS", name: "RBL Bank" },
  { symbol: "YESBANK.NS", name: "Yes Bank" },
  { symbol: "IOB.NS", name: "Indian Overseas Bank" },
  { symbol: "MAHABANK.NS", name: "Bank of Maharashtra" },
  { symbol: "UCOBANK.NS", name: "UCO Bank" },
  { symbol: "CENTRALBK.NS", name: "Central Bank of India" },
  { symbol: "PSB.NS", name: "Punjab & Sind Bank" },
  { symbol: "JKBANK.NS", name: "Jammu & Kashmir Bank" },
  { symbol: "KARURVYSYA.NS", name: "Karur Vysya Bank" },
  { symbol: "SOUTHBANK.NS", name: "South Indian Bank" },
  { symbol: "CSBBANK.NS", name: "CSB Bank" },
  { symbol: "DCBBANK.NS", name: "DCB Bank" },
  { symbol: "CUB.NS", name: "City Union Bank" },
  { symbol: "EQUITASBNK.NS", name: "Equitas Small Finance Bank" },
  { symbol: "UJJIVANSFB.NS", name: "Ujjivan Small Finance Bank" },
  { symbol: "MANAPPURAM.NS", name: "Manappuram Finance" },
  { symbol: "LICHSGFIN.NS", name: "LIC Housing Finance" },
  { symbol: "PEL.NS", name: "Piramal Enterprises" },
  { symbol: "IIFL.NS", name: "IIFL Finance" },
  { symbol: "POONAWALLA.NS", name: "Poonawalla Fincorp" },
  { symbol: "M&MFIN.NS", name: "Mahindra & Mahindra Financial Services" },
  { symbol: "ABCAPITAL.NS", name: "Aditya Birla Capital" },
  { symbol: "SUNDARMFIN.NS", name: "Sundaram Finance" },
  { symbol: "BAJAJHFL.NS", name: "Bajaj Housing Finance" },
  { symbol: "HUDCO.NS", name: "Housing & Urban Development Corp" },
  { symbol: "IRCTC.NS", name: "Indian Railway Catering" },
  { symbol: "IRCON.NS", name: "Ircon International" },
  { symbol: "RVNL.NS", name: "Rail Vikas Nigam" },
  { symbol: "RAILTEL.NS", name: "Railtel Corporation" },
  { symbol: "CONCOR.NS", name: "Container Corporation of India" },
  { symbol: "GRSE.NS", name: "Garden Reach Shipbuilders" },
  { symbol: "MAZDOCK.NS", name: "Mazagon Dock Shipbuilders" },
  { symbol: "COCHINSHIP.NS", name: "Cochin Shipyard" },
  { symbol: "BDL.NS", name: "Bharat Dynamics" },
  { symbol: "BEML.NS", name: "BEML" },
  { symbol: "HINDPETRO.NS", name: "Hindustan Petroleum" },
  { symbol: "OIL.NS", name: "Oil India" },
  { symbol: "PETRONET.NS", name: "Petronet LNG" },
  { symbol: "GUJGASLTD.NS", name: "Gujarat Gas" },
  { symbol: "IGL.NS", name: "Indraprastha Gas" },
  { symbol: "MGL.NS", name: "Mahanagar Gas" },
  { symbol: "GSPL.NS", name: "Gujarat State Petronet" },
  { symbol: "AEGISLOG.NS", name: "Aegis Logistics" },
  { symbol: "CASTROLIND.NS", name: "Castrol India" },
  { symbol: "MRPL.NS", name: "Mangalore Refinery" },
  { symbol: "CHENNPETRO.NS", name: "Chennai Petroleum" },
  { symbol: "NMDC.NS", name: "NMDC" },
  { symbol: "MOIL.NS", name: "MOIL" },
  { symbol: "SAIL.NS", name: "Steel Authority of India" },
  { symbol: "JINDALSTEL.NS", name: "Jindal Steel & Power" },
  { symbol: "JSWENERGY.NS", name: "JSW Energy" },
  { symbol: "JSL.NS", name: "Jindal Stainless" },
  { symbol: "APLAPOLLO.NS", name: "APL Apollo Tubes" },
  { symbol: "RATNAMANI.NS", name: "Ratnamani Metals" },
  { symbol: "WELCORP.NS", name: "Welspun Corp" },
  { symbol: "JINDALSAW.NS", name: "Jindal Saw" },
  { symbol: "MAHSEAMLES.NS", name: "Maharashtra Seamless" },
  { symbol: "NALCO.NS", name: "National Aluminium" },
  { symbol: "HINDZINC.NS", name: "Hindustan Zinc" },
  { symbol: "HINDCOPPER.NS", name: "Hindustan Copper" },
  { symbol: "GMDCLTD.NS", name: "Gujarat Mineral Development" },
  { symbol: "NATIONALUM.NS", name: "National Aluminium Co" },
  { symbol: "DALBHARAT.NS", name: "Dalmia Bharat" },
  { symbol: "ACC.NS", name: "ACC" },
  { symbol: "RAMCOCEM.NS", name: "The Ramco Cements" },
  { symbol: "JKCEMENT.NS", name: "JK Cement" },
  { symbol: "JKLAKSHMI.NS", name: "JK Lakshmi Cement" },
  { symbol: "HEIDELBERG.NS", name: "HeidelbergCement India" },
  { symbol: "BIRLACORPN.NS", name: "Birla Corporation" },
  { symbol: "NUVOCO.NS", name: "Nuvoco Vistas Corporation" },
  { symbol: "STARCEMENT.NS", name: "Star Cement" },
  { symbol: "INDIACEM.NS", name: "India Cements" },
  { symbol: "PRSMJOHNSN.NS", name: "Prism Johnson" },
  { symbol: "ORIENTCEM.NS", name: "Orient Cement" },
  { symbol: "GODREJPROP.NS", name: "Godrej Properties" },
  { symbol: "OBEROIRLTY.NS", name: "Oberoi Realty" },
  { symbol: "PRESTIGE.NS", name: "Prestige Estates" },
  { symbol: "BRIGADE.NS", name: "Brigade Enterprises" },
  { symbol: "PHOENIXLTD.NS", name: "Phoenix Mills" },
  { symbol: "SOBHA.NS", name: "Sobha" },
  { symbol: "MAHLIFE.NS", name: "Mahindra Lifespace" },
  { symbol: "SUNTECK.NS", name: "Sunteck Realty" },
  { symbol: "ANANTRAJ.NS", name: "Anant Raj" },
  { symbol: "NBCC.NS", name: "NBCC India" },
  { symbol: "IRB.NS", name: "IRB Infrastructure" },
  { symbol: "GMRINFRA.NS", name: "GMR Airports Infrastructure" },
  { symbol: "ASHOKLEY.NS", name: "Ashok Leyland" },
  { symbol: "BHARATFORG.NS", name: "Bharat Forge" },
  { symbol: "BALKRISIND.NS", name: "Balkrishna Industries" },
  { symbol: "MRF.NS", name: "MRF" },
  { symbol: "APOLLOTYRE.NS", name: "Apollo Tyres" },
  { symbol: "CEATLTD.NS", name: "CEAT" },
  { symbol: "JKTYRE.NS", name: "JK Tyre & Industries" },
  { symbol: "ESCORTS.NS", name: "Escorts Kubota" },
  { symbol: "SONACOMS.NS", name: "Sona BLW Precision" },
  { symbol: "EXIDEIND.NS", name: "Exide Industries" },
  { symbol: "AMARAJABAT.NS", name: "Amara Raja Energy" },
  { symbol: "ENDURANCE.NS", name: "Endurance Technologies" },
  { symbol: "TIINDIA.NS", name: "Tube Investments" },
  { symbol: "SCHAEFFLER.NS", name: "Schaeffler India" },
  { symbol: "ZFCVINDIA.NS", name: "ZF Commercial Vehicle" },
  { symbol: "SUNDRMFAST.NS", name: "Sundram Fasteners" },
  { symbol: "MINDAIND.NS", name: "UNO Minda" },
  { symbol: "BHARATGEAR.NS", name: "Bharat Gears" },
  { symbol: "BAJAJELEC.NS", name: "Bajaj Electricals" },
  { symbol: "WHIRLPOOL.NS", name: "Whirlpool of India" },
  { symbol: "VOLTAS.NS", name: "Voltas" },
  { symbol: "BLUESTARCO.NS", name: "Blue Star" },
  { symbol: "CROMPTON.NS", name: "Crompton Greaves Consumer" },
  { symbol: "POLYCAB.NS", name: "Polycab India" },
  { symbol: "KEI.NS", name: "KEI Industries" },
  { symbol: "FINCABLES.NS", name: "Finolex Cables" },
  { symbol: "DIXON.NS", name: "Dixon Technologies" },
  { symbol: "AMBER.NS", name: "Amber Enterprises" },
  { symbol: "HONAUT.NS", name: "Honeywell Automation" },
  { symbol: "CUMMINSIND.NS", name: "Cummins India" },
  { symbol: "THERMAX.NS", name: "Thermax" },
  { symbol: "KIRLOSENG.NS", name: "Kirloskar Oil Engines" },
  { symbol: "BHEL.NS", name: "Bharat Heavy Electricals" },
  { symbol: "SUZLON.NS", name: "Suzlon Energy" },
  { symbol: "INOXWIND.NS", name: "Inox Wind" },
  { symbol: "TDPOWERSYS.NS", name: "TD Power Systems" },
  { symbol: "GEPIL.NS", name: "GE Power India" },
  { symbol: "TRIVENI.NS", name: "Triveni Engineering" },
  { symbol: "ELGIEQUIP.NS", name: "Elgi Equipments" },
  { symbol: "GRINDWELL.NS", name: "Grindwell Norton" },
  { symbol: "CARBORUNIV.NS", name: "Carborundum Universal" },
  { symbol: "TIMKEN.NS", name: "Timken India" },
  { symbol: "SKFINDIA.NS", name: "SKF India" },
  { symbol: "NBVENTURES.NS", name: "Nava" },
  { symbol: "GRAPHITE.NS", name: "Graphite India" },
  { symbol: "HEG.NS", name: "HEG" },
  { symbol: "GUJALKALI.NS", name: "Gujarat Alkalies" },
  { symbol: "DEEPAKNTR.NS", name: "Deepak Nitrite" },
  { symbol: "AARTIIND.NS", name: "Aarti Industries" },
  { symbol: "NAVINFLUOR.NS", name: "Navin Fluorine" },
  { symbol: "SRF.NS", name: "SRF" },
  { symbol: "TATACHEM.NS", name: "Tata Chemicals" },
  { symbol: "GNFC.NS", name: "Gujarat Narmada Valley Fert" },
  { symbol: "GSFC.NS", name: "Gujarat State Fertilizers" },
  { symbol: "COROMANDEL.NS", name: "Coromandel International" },
  { symbol: "CHAMBLFERT.NS", name: "Chambal Fertilisers" },
  { symbol: "RCF.NS", name: "Rashtriya Chemicals" },
  { symbol: "FACT.NS", name: "Fertilizers & Chemicals Travancore" },
  { symbol: "NFL.NS", name: "National Fertilizers" },
  { symbol: "PIDILITIND.NS", name: "Pidilite Industries" },
  { symbol: "BASF.NS", name: "BASF India" },
  { symbol: "ATUL.NS", name: "Atul" },
  { symbol: "VINATIORGA.NS", name: "Vinati Organics" },
  { symbol: "ALKYLAMINE.NS", name: "Alkyl Amines Chemicals" },
  { symbol: "BALAMINES.NS", name: "Balaji Amines" },
  { symbol: "FINEORG.NS", name: "Fine Organic" },
  { symbol: "GALAXYSURF.NS", name: "Galaxy Surfactants" },
  { symbol: "CLEAN.NS", name: "Clean Science & Technology" },
  { symbol: "TATAELXSI.NS", name: "Tata Elxsi" },
  { symbol: "LTTS.NS", name: "L&T Technology Services" },
  { symbol: "LTIM.NS", name: "LTIMindtree" },
  { symbol: "MPHASIS.NS", name: "Mphasis" },
  { symbol: "PERSISTENT.NS", name: "Persistent Systems" },
  { symbol: "COFORGE.NS", name: "Coforge" },
  { symbol: "OFSS.NS", name: "Oracle Financial Services" },
  { symbol: "KPITTECH.NS", name: "KPIT Technologies" },
  { symbol: "TATATECH.NS", name: "Tata Technologies" },
  { symbol: "INTELLECT.NS", name: "Intellect Design Arena" },
  { symbol: "BSOFT.NS", name: "Birlasoft" },
  { symbol: "CYIENT.NS", name: "Cyient" },
  { symbol: "FSL.NS", name: "Firstsource Solutions" },
  { symbol: "ZENSARTECH.NS", name: "Zensar Technologies" },
  { symbol: "SONATSOFTW.NS", name: "Sonata Software" },
  { symbol: "RAMCOSYS.NS", name: "Ramco Systems" },
  { symbol: "NIITLTD.NS", name: "NIIT" },
  { symbol: "ROUTE.NS", name: "Route Mobile" },
  { symbol: "TANLA.NS", name: "Tanla Platforms" },
  { symbol: "HAPPSTMNDS.NS", name: "Happiest Minds Technologies" },
  { symbol: "MAPMYINDIA.NS", name: "C.E. Info Systems" },
  { symbol: "ZAGGLE.NS", name: "Zaggle Prepaid" },
  { symbol: "POLICYBZR.NS", name: "PB Fintech" },
  { symbol: "PAYTM.NS", name: "One 97 Communications" },
  { symbol: "NYKAA.NS", name: "FSN E-Commerce (Nykaa)" },
  { symbol: "DELHIVERY.NS", name: "Delhivery" },
  { symbol: "BLUEDART.NS", name: "Blue Dart Express" },
  { symbol: "TCI.NS", name: "Transport Corporation of India" },
  { symbol: "GATI.NS", name: "Gati" },
  { symbol: "MAHLOG.NS", name: "Mahindra Logistics" },
  { symbol: "VRLLOG.NS", name: "VRL Logistics" },
  { symbol: "ALLCARGO.NS", name: "Allcargo Logistics" },
  { symbol: "GESHIP.NS", name: "Great Eastern Shipping" },
  { symbol: "SCI.NS", name: "Shipping Corporation of India" },
  { symbol: "TCIEXP.NS", name: "TCI Express" },
  { symbol: "JUBLFOOD.NS", name: "Jubilant FoodWorks" },
  { symbol: "DEVYANI.NS", name: "Devyani International" },
  { symbol: "WESTLIFE.NS", name: "Westlife Foodworld" },
  { symbol: "SAPPHIRE.NS", name: "Sapphire Foods India" },
  { symbol: "VBL.NS", name: "Varun Beverages" },
  { symbol: "UBL.NS", name: "United Breweries" },
  { symbol: "RADICO.NS", name: "Radico Khaitan" },
  { symbol: "UNITDSPR.NS", name: "United Spirits" },
  { symbol: "MCDOWELL-N.NS", name: "United Spirits" },
  { symbol: "TASTYBITE.NS", name: "Tasty Bite Eatables" },
  { symbol: "BIKAJI.NS", name: "Bikaji Foods" },
  { symbol: "HATSUN.NS", name: "Hatsun Agro Product" },
  { symbol: "HERITGFOOD.NS", name: "Heritage Foods" },
  { symbol: "PARAGMILK.NS", name: "Parag Milk Foods" },
  { symbol: "KRBL.NS", name: "KRBL" },
  { symbol: "GODREJAGRO.NS", name: "Godrej Agrovet" },
  { symbol: "AVANTIFEED.NS", name: "Avanti Feeds" },
  { symbol: "VENKEYS.NS", name: "Venky's India" },
  { symbol: "EMAMILTD.NS", name: "Emami" },
  { symbol: "JYOTHYLAB.NS", name: "Jyothy Labs" },
  { symbol: "GILLETTE.NS", name: "Gillette India" },
  { symbol: "PGHH.NS", name: "Procter & Gamble Hygiene" },
  { symbol: "BAJAJCON.NS", name: "Bajaj Consumer Care" },
  { symbol: "VBL.NS", name: "Varun Beverages" },
  { symbol: "PAGEIND.NS", name: "Page Industries" },
  { symbol: "RELAXO.NS", name: "Relaxo Footwears" },
  { symbol: "BATAINDIA.NS", name: "Bata India" },
  { symbol: "METROBRAND.NS", name: "Metro Brands" },
  { symbol: "CAMPUS.NS", name: "Campus Activewear" },
  { symbol: "ABFRL.NS", name: "Aditya Birla Fashion" },
  { symbol: "VMART.NS", name: "V-Mart Retail" },
  { symbol: "SHOPERSTOP.NS", name: "Shoppers Stop" },
  { symbol: "TRENT.NS", name: "Trent" },
  { symbol: "ARVIND.NS", name: "Arvind" },
  { symbol: "KPRMILL.NS", name: "K.P.R. Mill" },
  { symbol: "WELSPUNLIV.NS", name: "Welspun Living" },
  { symbol: "TRIDENT.NS", name: "Trident" },
  { symbol: "VARDHACRLC.NS", name: "Vardhman Acrylics" },
  { symbol: "RAYMOND.NS", name: "Raymond" },
  { symbol: "GRASIM.NS", name: "Grasim Industries" },
  { symbol: "ALKEM.NS", name: "Alkem Laboratories" },
  { symbol: "BIOCON.NS", name: "Biocon" },
  { symbol: "AUROPHARMA.NS", name: "Aurobindo Pharma" },
  { symbol: "GLAND.NS", name: "Gland Pharma" },
  { symbol: "GLENMARK.NS", name: "Glenmark Pharmaceuticals" },
  { symbol: "LAURUSLABS.NS", name: "Laurus Labs" },
  { symbol: "MANKIND.NS", name: "Mankind Pharma" },
  { symbol: "ABBOTINDIA.NS", name: "Abbott India" },
  { symbol: "PFIZER.NS", name: "Pfizer" },
  { symbol: "SANOFI.NS", name: "Sanofi India" },
  { symbol: "GSK.NS", name: "GlaxoSmithKline Pharma" },
  { symbol: "IPCALAB.NS", name: "Ipca Laboratories" },
  { symbol: "JBCHEPHARM.NS", name: "JB Chemicals" },
  { symbol: "NATCOPHARM.NS", name: "Natco Pharma" },
  { symbol: "AJANTPHARM.NS", name: "Ajanta Pharma" },
  { symbol: "PPLPHARMA.NS", name: "Piramal Pharma" },
  { symbol: "SUVENPHAR.NS", name: "Suven Pharmaceuticals" },
  { symbol: "ERIS.NS", name: "Eris Lifesciences" },
  { symbol: "FORTIS.NS", name: "Fortis Healthcare" },
  { symbol: "MAXHEALTH.NS", name: "Max Healthcare Institute" },
  { symbol: "NH.NS", name: "Narayana Hrudayalaya" },
  { symbol: "MEDPLUS.NS", name: "MedPlus Health Services" },
  { symbol: "METROPOLIS.NS", name: "Metropolis Healthcare" },
  { symbol: "DRLAL.NS", name: "Dr. Lal PathLabs" },
  { symbol: "THYROCARE.NS", name: "Thyrocare Technologies" },
  { symbol: "VIJAYA.NS", name: "Vijaya Diagnostic Centre" },
  { symbol: "POLYMED.NS", name: "Poly Medicure" },
  { symbol: "KIMS.NS", name: "Krishna Institute of Medical" },
  { symbol: "RAINBOW.NS", name: "Rainbow Children's Medicare" },
  { symbol: "GLAXO.NS", name: "GlaxoSmithKline Consumer" },
  { symbol: "PROCTER.NS", name: "Procter & Gamble" },
  { symbol: "JUBLPHARMA.NS", name: "Jubilant Pharmova" },
  { symbol: "CAPLIPOINT.NS", name: "Caplin Point Laboratories" },
  { symbol: "GRANULES.NS", name: "Granules India" },
  { symbol: "STAR.NS", name: "Strides Pharma Science" },
  { symbol: "FDC.NS", name: "FDC" },
  { symbol: "WOCKPHARMA.NS", name: "Wockhardt" },
  { symbol: "INDOCO.NS", name: "Indoco Remedies" },
  { symbol: "SEQUENT.NS", name: "Sequent Scientific" },
  { symbol: "MARKSANS.NS", name: "Marksans Pharma" },
  { symbol: "ORCHPHARMA.NS", name: "Orchid Pharma" },
  { symbol: "NEULANDLAB.NS", name: "Neuland Laboratories" },
  { symbol: "SUPRIYA.NS", name: "Supriya Lifescience" },
  { symbol: "AETHER.NS", name: "Aether Industries" },
  { symbol: "TATAPOWER.NS", name: "Tata Power" },
  { symbol: "NHPC.NS", name: "NHPC" },
  { symbol: "SJVN.NS", name: "SJVN" },
  { symbol: "CESC.NS", name: "CESC" },
  { symbol: "NLCINDIA.NS", name: "NLC India" },
  { symbol: "RPOWER.NS", name: "Reliance Power" },
  { symbol: "TATACOMM.NS", name: "Tata Communications" },
  { symbol: "IDEA.NS", name: "Vodafone Idea" },
  { symbol: "INDUSTOWER.NS", name: "Indus Towers" },
  { symbol: "STLTECH.NS", name: "Sterlite Technologies" },
  { symbol: "HFCL.NS", name: "HFCL" },
  { symbol: "ITI.NS", name: "ITI" },
  { symbol: "GTPL.NS", name: "GTPL Hathway" },
  { symbol: "HATHWAY.NS", name: "Hathway Cable" },
  { symbol: "DBCORP.NS", name: "D.B. Corp" },
  { symbol: "JAGRAN.NS", name: "Jagran Prakashan" },
  { symbol: "PVRINOX.NS", name: "PVR INOX" },
  { symbol: "SUNTV.NS", name: "Sun TV Network" },
  { symbol: "ZEEL.NS", name: "Zee Entertainment" },
  { symbol: "TIPSINDLTD.NS", name: "Tips Industries" },
  { symbol: "SAREGAMA.NS", name: "Saregama India" },
  { symbol: "NAZARA.NS", name: "Nazara Technologies" },
  { symbol: "ONMOBILE.NS", name: "OnMobile Global" },
  { symbol: "NETWORK18.NS", name: "Network18 Media" },
  { symbol: "TV18BRDCST.NS", name: "TV18 Broadcast" },
  { symbol: "DISHTV.NS", name: "Dish TV India" },
  { symbol: "BALRAMCHIN.NS", name: "Balrampur Chini" },
  { symbol: "DHAMPURSUG.NS", name: "Dhampur Sugar" },
  { symbol: "DALMIASUG.NS", name: "Dalmia Bharat Sugar" },
  { symbol: "EIDPARRY.NS", name: "EID Parry" },
  { symbol: "RENUKA.NS", name: "Shree Renuka Sugars" },
  { symbol: "BAJAJHIND.NS", name: "Bajaj Hindusthan Sugar" },
  { symbol: "CCL.NS", name: "CCL Products" },
  { symbol: "TATACOFFEE.NS", name: "Tata Coffee" },
  { symbol: "MCLEODRUSS.NS", name: "McLeod Russel India" },
  { symbol: "JAYNECOIND.NS", name: "Jayaswal Neco Industries" },
  { symbol: "WELSPUNIND.NS", name: "Welspun India" },
  { symbol: "HIMATSEIDE.NS", name: "Himatsingka Seide" },
  { symbol: "SIYSIL.NS", name: "Siyaram Silk Mills" },
  { symbol: "VTL.NS", name: "Vardhman Textiles" },
  { symbol: "RTNINDIA.NS", name: "RattanIndia Enterprises" },
  { symbol: "JPPOWER.NS", name: "Jaiprakash Power Ventures" },
  { symbol: "JPASSOCIAT.NS", name: "Jaiprakash Associates" },
  { symbol: "GVKPIL.NS", name: "GVK Power & Infra" },
  { symbol: "ADANITRANS.NS", name: "Adani Energy Solutions" },
  { symbol: "ADANITOTAL.NS", name: "Adani Total Gas" },
  { symbol: "ADANIWILMAR.NS", name: "Adani Wilmar" },
  { symbol: "ATGL.NS", name: "Adani Total Gas" },
  { symbol: "FLUOROCHEM.NS", name: "Gujarat Fluorochemicals" },
  { symbol: "INOXINDIA.NS", name: "INOX India" },
  { symbol: "BORORENEW.NS", name: "Borosil Renewables" },
  { symbol: "PRAJIND.NS", name: "Praj Industries" },
  { symbol: "ASTRAL.NS", name: "Astral" },
  { symbol: "SUPREMEIND.NS", name: "Supreme Industries" },
  { symbol: "FINOLEXIND.NS", name: "Finolex Industries" },
  { symbol: "JAINIRRIG.NS", name: "Jain Irrigation Systems" },
  { symbol: "KAJARIACER.NS", name: "Kajaria Ceramics" },
  { symbol: "SOMANYCERA.NS", name: "Somany Ceramics" },
  { symbol: "CERA.NS", name: "Cera Sanitaryware" },
  { symbol: "GREENPLY.NS", name: "Greenply Industries" },
  { symbol: "CENTURYPLY.NS", name: "Century Plyboards" },
  { symbol: "GREENPANEL.NS", name: "Greenpanel Industries" },
  { symbol: "ACI.NS", name: "Archean Chemical Industries" },
  { symbol: "EPL.NS", name: "EPL" },
  { symbol: "POLYPLEX.NS", name: "Polyplex Corporation" },
  { symbol: "COSMOFIRST.NS", name: "Cosmo First" },
  { symbol: "UFLEX.NS", name: "UFlex" },
  { symbol: "JINDWORLD.NS", name: "Jindal Worldwide" },
  { symbol: "TIRUMALCHM.NS", name: "Thirumalai Chemicals" },
  { symbol: "BAYERCROP.NS", name: "Bayer Cropscience" },
  { symbol: "UPL.NS", name: "UPL" },
  { symbol: "PIRAMALENT.NS", name: "Piramal Enterprises" },
  { symbol: "RALLIS.NS", name: "Rallis India" },
  { symbol: "DHANUKA.NS", name: "Dhanuka Agritech" },
  { symbol: "INSECTICID.NS", name: "Insecticides India" },
  { symbol: "SHARDACROP.NS", name: "Sharda Cropchem" },
  { symbol: "SUMICHEM.NS", name: "Sumitomo Chemical India" },
  { symbol: "EIHOTEL.NS", name: "EIH" },
  { symbol: "CHALET.NS", name: "Chalet Hotels" },
  { symbol: "LEMONTREE.NS", name: "Lemon Tree Hotels" },
  { symbol: "MAHINDCIE.NS", name: "Mahindra CIE Automotive" },
  { symbol: "RAJESHEXPO.NS", name: "Rajesh Exports" },
  { symbol: "TITAGARH.NS", name: "Titagarh Rail Systems" },
  { symbol: "TEXRAIL.NS", name: "Texmaco Rail" },
  { symbol: "JWL.NS", name: "Jupiter Wagons" },
  { symbol: "IFCI.NS", name: "IFCI" },
  { symbol: "IIFLSEC.NS", name: "IIFL Securities" },
  { symbol: "MOTILALOFS.NS", name: "Motilal Oswal Financial" },
  { symbol: "ANGELONE.NS", name: "Angel One" },
  { symbol: "5PAISA.NS", name: "5Paisa Capital" },
  { symbol: "CDSL.NS", name: "Central Depository Services" },
  { symbol: "MCX.NS", name: "Multi Commodity Exchange" },
  { symbol: "BSE.NS", name: "BSE" },
  { symbol: "CAMS.NS", name: "Computer Age Management Services" },
  { symbol: "KFINTECH.NS", name: "KFin Technologies" },
  { symbol: "UTIAMC.NS", name: "UTI Asset Management" },
  { symbol: "NIPPONLIFE.NS", name: "Nippon Life India Asset" },
  { symbol: "ABSLAMC.NS", name: "Aditya Birla Sun Life AMC" },
  { symbol: "STARHEALTH.NS", name: "Star Health Insurance" },
  { symbol: "NIACL.NS", name: "New India Assurance" },
  { symbol: "GICRE.NS", name: "General Insurance Corp" },
  { symbol: "MEDANTA.NS", name: "Global Health" },
  { symbol: "HOMEFIRST.NS", name: "Home First Finance" },
  { symbol: "AAVAS.NS", name: "Aavas Financiers" },
  { symbol: "REPCO.NS", name: "Repco Home Finance" },
  { symbol: "CANFINHOME.NS", name: "Can Fin Homes" },
  { symbol: "PNBHOUSING.NS", name: "PNB Housing Finance" },
  { symbol: "GICHSGFIN.NS", name: "GIC Housing Finance" },
  { symbol: "EDELWEISS.NS", name: "Edelweiss Financial" },
  { symbol: "JSWINFRA.NS", name: "JSW Infrastructure" },
  { symbol: "GPIL.NS", name: "Godawari Power & Ispat" },
  { symbol: "JSWHL.NS", name: "JSW Holdings" },
  { symbol: "RHIM.NS", name: "RHI Magnesita India" },
  { symbol: "MAITHAN.NS", name: "Maithan Alloys" },
  { symbol: "JINDALPOLY.NS", name: "Jindal Poly Films" },
  { symbol: "VGUARD.NS", name: "V-Guard Industries" },
  { symbol: "ORIENTELEC.NS", name: "Orient Electric" },
  { symbol: "SYMPHONY.NS", name: "Symphony" },
  { symbol: "TTKPRESTIG.NS", name: "TTK Prestige" },
  { symbol: "STOVEKRAFT.NS", name: "Stove Kraft" },
  { symbol: "HAWKINCOOK.NS", name: "Hawkins Cookers" },
  { symbol: "BUTTERFLY.NS", name: "Butterfly Gandhimathi" },
  { symbol: "RAJRATAN.NS", name: "Rajratan Global Wire" },
  { symbol: "USHAMART.NS", name: "Usha Martin" },
  { symbol: "BANSALWIRE.NS", name: "Bansal Wire Industries" },
  { symbol: "RKFORGE.NS", name: "Ramkrishna Forgings" },
  { symbol: "HAPPYFORGE.NS", name: "Happy Forgings" },
  { symbol: "POWERINDIA.NS", name: "Hitachi Energy India" },
  { symbol: "GMMPFAUDLR.NS", name: "GMM Pfaudler" },
  { symbol: "ENGINERSIN.NS", name: "Engineers India" },
  { symbol: "AIAENG.NS", name: "AIA Engineering" },
  { symbol: "ESABINDIA.NS", name: "ESAB India" },
  { symbol: "GREAVESCOT.NS", name: "Greaves Cotton" },
  { symbol: "ELECON.NS", name: "Elecon Engineering" },
  { symbol: "ISGEC.NS", name: "Isgec Heavy Engineering" },
  { symbol: "KIRLPNU.NS", name: "Kirloskar Pneumatic" },
  { symbol: "KIRLOSBROS.NS", name: "Kirloskar Brothers" },
  { symbol: "WABAG.NS", name: "VA Tech Wabag" },
  { symbol: "ION.NS", name: "ION Exchange" },
  { symbol: "VATECHWAB.NS", name: "VA Tech Wabag" },
  { symbol: "EIMCOELECO.NS", name: "Eimco Elecon" },
  { symbol: "JYOTICNC.NS", name: "Jyoti CNC Automation" },
  { symbol: "MTARTECH.NS", name: "MTAR Technologies" },
  { symbol: "RATEGAIN.NS", name: "RateGain Travel" },
  { symbol: "EASEMYTRIP.NS", name: "Easy Trip Planners" },
  { symbol: "YATRA.NS", name: "Yatra Online" },
  { symbol: "SPICEJET.NS", name: "SpiceJet" },
  { symbol: "JETAIRWAYS.NS", name: "Jet Airways" },
  { symbol: "GLOBE.NS", name: "Globe Civil Projects" },
  { symbol: "HGINFRA.NS", name: "H.G. Infra Engineering" },
  { symbol: "KNRCON.NS", name: "KNR Constructions" },
  { symbol: "PNCINFRA.NS", name: "PNC Infratech" },
  { symbol: "DBL.NS", name: "Dilip Buildcon" },
  { symbol: "JKIL.NS", name: "J Kumar Infraprojects" },
  { symbol: "NCC.NS", name: "NCC" },
  { symbol: "ITDC.NS", name: "India Tourism Development" },
  { symbol: "RITES.NS", name: "RITES" },
  { symbol: "MAHSCOOTER.NS", name: "Maharashtra Scooters" },
  { symbol: "MASTEK.NS", name: "Mastek" },
  { symbol: "QUESS.NS", name: "Quess Corp" },
  { symbol: "TEAMLEASE.NS", name: "TeamLease Services" },
  { symbol: "SIS.NS", name: "SIS" },
  { symbol: "AFFLE.NS", name: "Affle India" },
  { symbol: "INDIAMART.NS", name: "IndiaMART InterMESH" },
  { symbol: "JUSTDIAL.NS", name: "Just Dial" },
  { symbol: "MATRIMONY.NS", name: "Matrimony.com" },
  { symbol: "LATENTVIEW.NS", name: "Latent View Analytics" },
  { symbol: "NEWGEN.NS", name: "Newgen Software" },
  { symbol: "RSYSTEMS.NS", name: "R Systems International" },
  { symbol: "ECLERX.NS", name: "eClerx Services" },
  { symbol: "WTCL.NS", name: "WTC Logistics" },
  { symbol: "GMRP&UI.NS", name: "GMR Power & Urban Infra" },
  { symbol: "KALPATPOWR.NS", name: "Kalpataru Projects" },
  { symbol: "KEC.NS", name: "KEC International" },
  { symbol: "PATELENG.NS", name: "Patel Engineering" },
  { symbol: "AHLUCONT.NS", name: "Ahluwalia Contracts" },
  { symbol: "ITDCEM.NS", name: "ITD Cementation" },
  { symbol: "CAPACITE.NS", name: "Capacit'e Infraprojects" },
  { symbol: "ASHIANA.NS", name: "Ashiana Housing" },
  { symbol: "ARVSMART.NS", name: "Arvind SmartSpaces" },
  { symbol: "PURVA.NS", name: "Puravankara" },
  { symbol: "KOLTEPATIL.NS", name: "Kolte-Patil Developers" },
  { symbol: "MAHEPC.NS", name: "Mahindra EPC Irrigation" },
  { symbol: "EMSLIMITED.NS", name: "EMS" },
  { symbol: "ALLCARGO.NS", name: "Allcargo Logistics" },
  { symbol: "SAFARI.NS", name: "Safari Industries" },
  { symbol: "VIPIND.NS", name: "VIP Industries" },
  { symbol: "ETERNAL.NS", name: "Eternal" },
  { symbol: "SWIGGY.NS", name: "Swiggy" },
  { symbol: "FIRSTCRY.NS", name: "Brainbees Solutions (FirstCry)" },
  { symbol: "OLAELEC.NS", name: "Ola Electric Mobility" },
  { symbol: "NIVABUPA.NS", name: "Niva Bupa Health Insurance" },
  { symbol: "WAAREE.NS", name: "Waaree Energies" },
  { symbol: "PREMIER.NS", name: "Premier Energies" },
  { symbol: "ACME.NS", name: "ACME Solar Holdings" },
  { symbol: "SAGILITY.NS", name: "Sagility India" },
  { symbol: "NTPCGREEN.NS", name: "NTPC Green Energy" },
  { symbol: "ZINKA.NS", name: "Zinka Logistics (BlackBuck)" },
  { symbol: "INVENTURUS.NS", name: "Inventurus Knowledge" },
  { symbol: "VISHAL.NS", name: "Vishal Mega Mart" },
  { symbol: "MOBIKWIK.NS", name: "One MobiKwik Systems" },
  { symbol: "INDOSTAR.NS", name: "IndoStar Capital Finance" },
];

// Deduplicate by symbol while keeping first occurrence.
const seen = new Set<string>();
export const NSE_500_UNIQUE: NseStock[] = NSE_500.filter((s) => {
  if (seen.has(s.symbol)) return false;
  seen.add(s.symbol);
  return true;
});

// Top 5 Indian indices (Yahoo Finance symbols).
export const INDIA_INDICES: NseStock[] = [
  { symbol: "^NSEI", name: "NIFTY 50" },
  { symbol: "^BSESN", name: "BSE SENSEX" },
  { symbol: "^NSEBANK", name: "NIFTY BANK" },
  { symbol: "^CNXIT", name: "NIFTY IT" },
  { symbol: "NIFTY_MIDCAP_100.NS", name: "NIFTY MIDCAP 100" },
];

// Top 5 cryptocurrencies (Yahoo Finance symbols, USD pairs).
export const TOP_CRYPTO: NseStock[] = [
  { symbol: "BTC-USD", name: "Bitcoin" },
  { symbol: "ETH-USD", name: "Ethereum" },
  { symbol: "BNB-USD", name: "BNB" },
  { symbol: "SOL-USD", name: "Solana" },
  { symbol: "XRP-USD", name: "XRP" },
];

export const FULL_UNIVERSE: NseStock[] = [
  ...INDIA_INDICES,
  ...NSE_500_UNIQUE,
];
